---
title: "Statistical Tests for Python Project"
output: html_document
date: "2024-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Texas P Values

These are the tests done for the various graphs for the Texas case study. They include: t-tests for differences between means, and Chi-squared tests to test whether the column variables are "significantly associated" with each other. 

```{r Texas}
Texas =  read.csv("~/NYCDSA/First Project/Git_Workspace/College_Scorecard_Data/Data/Texas_Retention.csv")
t.test(Overall.GPA ~ Retention, data = Texas)
#mean in group Not retained     mean in group Retained 
                  #3.023611                   3.113918 #p-value < 2.2e-16
t.test(High.School.GPA ~ Retention, data = Texas)
#mean in group Not retained     mean in group Retained 
                  #3.340696                   3.338728 #p-value = 0.8433
chisq.test(table(Texas$Change.in.GPA,Texas$Retention))
#p-value = 0.2266
chisq.test(table(Texas$Received.Financial.Aid,Texas$Retention))
#p-value = 3.376e-05
```
```{r Scoreboard Debt Anovas}
Scorecard = read.csv("~/NYCDSA/First Project/Git_Workspace/College_Scorecard_Data/Data/Trimmed_Scorecard.csv")
Scorecard$PCTFLOAN = as.numeric(as.character(Scorecard$PCTFLOAN))
Scorecard$RET_FT4_POOLED = as.numeric(as.character(Scorecard$RET_FT4_POOLED))
Scorecard$C150_4_POOLED = as.numeric(as.character(Scorecard$C150_4_POOLED))
Scorecard$C150_4_LOANNOPELL = as.numeric(as.character(Scorecard$C150_4_LOANNOPELL))
Scorecard$C150_4_PELL = as.numeric(as.character(Scorecard$C150_4_PELL))
#aov(C150_4_POOLED~ PCTFLOAN, data = Scorecard)
#aov(RET_FT4_POOLED~ PCTFLOAN, data = Scorecard)
#aov(C150_4_LOANNOPELL~ PCTFLOAN, data = Scorecard)
#aov(C150_4_PELL~ PCTFLOAN, data = Scorecard)
Anova(lm(C150_4_POOLED  ~ PCTFLOAN, data = Scorecard)) # P value < 2.2e-16
Anova(lm(RET_FT4_POOLED  ~ PCTFLOAN, data = Scorecard)) # P value 0.08323
Anova(lm(C150_4_LOANNOPELL  ~ PCTFLOAN, data = Scorecard)) # P value < 2.2e-16
Anova(lm(C150_4_PELL  ~ PCTFLOAN, data = Scorecard)) # P value < 2.2e-16
```
```{r Scoreboard Income Anovas (Ignore?)}
Scorecard$AVGFAMINC = as.numeric(as.character(Scorecard$AVGFAMINC))
Scorecard$FAMINC_IND = as.numeric(as.character(Scorecard$FAMINC_IND))
#Scorecard$RET_FT4_POOLED = label_percent()(Scorecard$RET_FT4_POOLED)
Anova(lm(C150_4_POOLED  ~ AVGFAMINC, data = Scorecard)) #P value < 2.2e-16
Anova(lm(RET_FT4_POOLED  ~ AVGFAMINC, data = Scorecard)) #P value < 2.2e-16
Anova(lm(C150_4_POOLED  ~ FAMINC_IND, data = Scorecard)) #P value 0.07029 
Anova(lm(RET_FT4_POOLED  ~ FAMINC_IND, data = Scorecard)) #P value 0.006934
```
```{r Scorecard Income Beta Regression/Individual}
summary(gamlss(C150_4_POOLED ~ FAMINC_IND, data=na.omit(Scorecard)))
#T value -2.298    P value 0.0216
summary(gamlss(RET_FT4_POOLED ~ FAMINC_IND, data=na.omit(Scorecard)))
#T value 3.933 P value 8.55e-05
```
```{rScorecard Income Beta Regression/Family}
summary(gamlss(C150_4_POOLED ~ AVGFAMINC, data=na.omit(Scorecard)))
#T value 17.18   P value <2e-16
summary(gamlss(RET_FT4_POOLED ~ AVGFAMINC, data=na.omit(Scorecard)))
#T value 23.92   P value <2e-16
```
```{r Scorecard Tuition}
Scorecard$Instate_Tuition = as.numeric(as.character(Scorecard$Instate_Tuition))
Scorecard$Outstate_Tuition = as.numeric(as.character(Scorecard$Outstate_Tuition))
summary(gamlss(RET_FT4_POOLED ~ Instate_Tuition, data=na.omit(Scorecard)))
#T value 24.31   P value <2e-16
summary(gamlss(RET_FT4_POOLED ~ Outstate_Tuition, data=na.omit(Scorecard)))
#T value 33.35   P value <2e-16
```




